# Generated by Django 5.0.1 on 2024-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(                        
            name='Emp',              
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),                          
                ('ename', models.CharField(max_length=255)),               
                ('esal', models.FileField(upload_to='')),                
                ('eaddress', models.CharField(max_length=255)),             
            ],
        ),
    ]
